name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "qudsiramiz@gmail.com"
          git config --global user.name "qudsiramiz"

      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r src/requirements.txt

      - name: Set up auth token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run gh-pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./docs/_build/html  # Path to the folder you want to deploy

      - name: Build the documentation
        run: sphinx-build -b html src docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          user_name: GitHub Actions